# Generated by Django 5.2.12 on 2026-03-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название идеи')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(choices=[('romantic', 'Романтика'), ('adventure', 'Приключения'), ('creative', 'Творчество'), ('culture', 'Культура'), ('active', 'Активный отдых'), ('home', 'Домашний уют')], default='romantic', max_length=20, verbose_name='Категория')),
                ('budget', models.CharField(choices=[('free', 'Бесплатно'), ('low', 'Бюджетно (до 1000₽)'), ('medium', 'Средний (1000-3000₽)'), ('high', 'Высокий (3000-10000₽)'), ('luxury', 'Премиум (10000₽+)')], default='medium', max_length=20, verbose_name='Бюджет')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение')),
                ('duration_hours', models.IntegerField(default=2, verbose_name='Длительность (часы)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Идея для свидания',
                'verbose_name_plural': 'Идеи для свиданий',
                'ordering': ['-created_at'],
            },
        ),
    ]
