# Generated by Django 5.2.12 on 2026-05-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_idea_options_idea_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['-created_at'], 'verbose_name': 'Идея для свидания', 'verbose_name_plural': 'Идеи для свиданий'},
        ),
        migrations.AddField(
            model_name='idea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ideas_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='idea',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='ideas', to='pages.tag', verbose_name='Теги'),
        ),
    ]
